echo "You should have asnmap installed"
echo ""
echo "Ensure you are authenticated:"
echo 'export PDCP_API_KEY="apikey"'
echo ""
companies=(
	"symantec.com"
	"mcafee.com"
	"trendmicro.com"
	"paloaltonetworks.com"
	"cisco.com"
	"checkpoint.com"
	"fortinet.com"
	"fireeye.com"
	"crowdstrike.com"
	"proofpoint.com"
	"sophos.com"
	"kaspersky.com"
	"bitdefender.com"
	"rapid7.com"
	"f-secure.com"
	"ibm.com/security"
	"sentinelone.com"
	"carbonblack.com"
	"sonicwall.com"
	"zscaler.com"
	"google.com"
	"microsoft.com"
	"apple.com"
	"amazon.com"
	"facebook.com"
	"ibm.com"
	"oracle.com"
	"intel.com"
	"hp.com"
	"dell.com"
	"vmware.com"
	"adobe.com"
	"salesforce.com"
	"nvidia.com"
	"qualcomm.com"
	"samsung.com"
	"cloudflare.com"
	"avast.com"
	"symantecliveupdate.com"
	"secure.mcafee.com"
	"fortiguard.com"
	"eset.com"
	"malwarebytes.com"
	"barracuda.com"
	"webroot.com"
	"cyberark.com"
	"darktrace.com"
	"mimecast.com"
	"varonis.com"
	"logrhythm.com"
	"cylance.com"
	"netspi.com"
	"mandiant.com"
	"trellix.com"
	"ATHSec.co"
	"sentinalone.com"
	"snyk.com"
	"checkpoint.com"
	"Malwarebytes.com"
	"virustotal.com"
	"Cybereason.com"
	"watchguard.com"
	"trellix.com"
	"tufin.com"
)

# Loop through each company name
for company in "${companies[@]}"; do
    # Use asnmap to search for IP addresses associated with the company name
    ips=$(asnmap -d "$company" -silent)
    echo "----$company----" >> ips-out.txt

    # Loop through each IP address found
    while IFS= read -r ip; do
        # Add the IP address to IP tables for dropping incoming packets
        echo "$ip" >> ips-out.txt
    done <<< "$ips"
done
